[phases.install]
apt = []
cmds = ["npm install", "cd backend && npm install", "cd frontend && npm install"]

[phases.build]
cmds = ["cd frontend && npm run build", "rm -rf backend/public", "mkdir -p backend/public", "cp -r frontend/dist/* backend/public/"]

[start]
cmd = "cd backend && node server.js"